apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: drycc-controller-cronjob-daily
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  failedJobsHistoryLimit: 1
  schedule: "0 */1 * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccount: drycc-controller
          containers:
          - image: {{.Values.image_registry}}/{{.Values.org}}/controller:{{.Values.image_tag}}
            imagePullPolicy: {{.Values.pull_policy}}
            name: drycc-controller-measure-app
            command:
              - /bin/bash
              - -c
            args:
              - python -u /app/manage.py measure_app
            {{- include "controller.envs" . | indent 12 }}
            {{- include "controller.volumeMounts" . | indent 12 }}
          {{- include "controller.volumes" . | indent 10 }}
